/**
* LiberatePDF2 Microservice
* Microservice for LiberatePDF2
*
* The version of the OpenAPI document: 0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package de.debuglevel.liberatepdf2.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param maximumMultipartUploadSize 
 * @param maximumRequestSize 
 * @param maximumMultipartFileSize 
 * @param multipartEnabled 
 */

data class GetConfigurationResponse (
    @Json(name = "maximumMultipartUploadSize")
    val maximumMultipartUploadSize: kotlin.Long? = null,
    @Json(name = "maximumRequestSize")
    val maximumRequestSize: kotlin.Long? = null,
    @Json(name = "maximumMultipartFileSize")
    val maximumMultipartFileSize: kotlin.Long? = null,
    @Json(name = "multipartEnabled")
    val multipartEnabled: kotlin.Boolean? = null
)

