/**
* LiberatePDF2 Microservice
* Microservice for LiberatePDF2
*
* The version of the OpenAPI document: 0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package de.debuglevel.liberatepdf2.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param storedItems 
 * @param processedItems 
 * @param failedItems 
 * @param successfulItems 
 */

data class GetStatisticResponse (
    @Json(name = "storedItems")
    val storedItems: kotlin.Long? = null,
    @Json(name = "processedItems")
    val processedItems: kotlin.Long? = null,
    @Json(name = "failedItems")
    val failedItems: kotlin.Long? = null,
    @Json(name = "successfulItems")
    val successfulItems: kotlin.Long? = null
)

