version: '3'
services:
  gateway:
    build: nginx-gateway
    image: liberatepdf2-gateway
    ports:
      - "8080:80"
  angular:
    build: angular
    image: liberatepdf2-angular
    # ports:
    #   - "8082:80"
    environment:
      - API_URL=http://localhost:8080/api/
  rest:
    build: microservice
    image: liberatepdf2-microservice
    # ports:
    #   - "8081:80"
    environment:
      # number of threads for parallel PDF transformation
      - APP_LIBERATEPDF2_TRANSFORMATION_WORKER_THREADS=4
      # set the maximum size for requests
      - MICRONAUT_SERVER_MAX_REQUEST_SIZE=20mb
      - MICRONAUT_SERVER_MULTIPART_MAX_FILE_SIZE=20mb
      # port 80 is actually already defined as default for docker as ENV in Dockerfile
      - MICRONAUT_SERVER_PORT=80
#      # log as JSON
#      - LOG_APPENDER=json-stdout
#      # enable health check if Consul is used
#      - CONSUL_CLIENT_HEALTH_CHECK=true
#      # register this service on Consul
#      - CONSUL_CLIENT_REGISTRATION_ENABLED=true
#      # search for services on Consul
#      - CONSUL_CLIENT_DISCOVERY_ENABLED=true
#      # Consul server
#      - CONSUL_HOST=consul
#      - CONSUL_PORT=8500
#
#  # Service registration and discovery with Consul
#  consul:
#    image: consul:1.8.4
#    ports:
#      - "8500:8500"