version: '3'
services:
  angular:
    build: angular
    image: liberatepdf2-angular
    ports:
      - "8082:80"
  rest:
    build: microservice
    image: liberatepdf2-microservice
    ports:
      - "8081:80"
    environment:
      # port 80 is actually already defined as default for docker as ENV in Dockerfile
      - MICRONAUT_SERVER_PORT=80
#      # log as JSON
#      - LOG_APPENDER=json-stdout
#      # enable health check if Consul is used
#      - CONSUL_CLIENT_HEALTH_CHECK=true
#      # register this service on Consul
#      - CONSUL_CLIENT_REGISTRATION_ENABLED=true
#      # search for services on Consul
#      - CONSUL_CLIENT_DISCOVERY_ENABLED=true
#      # Consul server
#      - CONSUL_HOST=consul
#      - CONSUL_PORT=8500
#
#  # Service registration and discovery with Consul
#  consul:
#    image: consul:1.8.4
#    ports:
#      - "8500:8500"