/**
 * LiberatePDF2 Microservice
 * Microservice for LiberatePDF2
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MediaType } from './media-type';


export interface StreamedFile { 
    lastModified?: number;
    length?: number;
    mediaType?: MediaType;
    inputStream?: object;
}

