/**
 * LiberatePDF2 Microservice
 * Microservice for LiberatePDF2
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package de.debuglevel.liberatepdf2.restclient.models


import com.squareup.moshi.Json

/**
 *
 * @param registered
 * @param name
 * @param aliases
 */

data class Charset(
    @Json(name = "registered")
    val registered: kotlin.Boolean? = null,
    @Json(name = "name")
    val name: kotlin.String? = null,
    @Json(name = "aliases")
    val aliases: kotlin.collections.List<kotlin.String>? = null
)

