/**
 * LiberatePDF2 Microservice
 * Microservice for LiberatePDF2
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package de.debuglevel.liberatepdf2.restclient.models

import com.squareup.moshi.Json

/**
 *
 * @param name
 * @param type
 * @param subtype
 * @param extension
 * @param parameters
 * @param quality
 * @param qualityAsNumber
 * @param version
 * @param charset
 * @param textBased
 */

data class MediaType(
    @Json(name = "name")
    val name: kotlin.String? = null,
    @Json(name = "type")
    val type: kotlin.String? = null,
    @Json(name = "subtype")
    val subtype: kotlin.String? = null,
    @Json(name = "extension")
    val extension: kotlin.String? = null,
    @Json(name = "parameters")
    val parameters: kotlin.collections.List<kotlin.String>? = null,
    @Json(name = "quality")
    val quality: kotlin.String? = null,
    @Json(name = "qualityAsNumber")
    val qualityAsNumber: java.math.BigDecimal? = null,
    @Json(name = "version")
    val version: kotlin.String? = null,
    @Json(name = "charset")
    val charset: Charset? = null,
    @Json(name = "textBased")
    val textBased: kotlin.Boolean? = null
)

